name: Docker Build Images

run-name: Build Keycloak v${{ inputs.version }} ${{ inputs.triggered_by && format('({0})', inputs.triggered_by) || '' }}

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Keycloak version'
                required: true
                type: string
            triggered_by:
                description: 'Trigger source (e.g., VersionPulse)'
                required: false
                type: string
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/keycloak

concurrency:
    group: build-docker-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Docker metadata
                id: keycloak
                uses: docker/metadata-action@v4
                with:
                    images: ${{ env.IMAGE_NAME }}
                    tags: |
                        type=raw,value=${{ inputs.version }}
                        type=raw,value=latest
                    labels: |
                        org.opencontainers.image.description=Open Source Identity and Access Management
                        org.opencontainers.image.title=Keycloak
                        org.opencontainers.image.version=${{ inputs.version }}

            -   name: Print build options (dry run)
                env:
                    VERSION: "${{ inputs.version }}"
                    TAG: "${{ env.IMAGE_NAME }}:${{ inputs.version }}"
                run: |
                    cat "${{ steps.keycloak.outputs.bake-file }}"
                    docker buildx bake  -f docker-bake.hcl -f "${{ steps.keycloak.outputs.bake-file }}" --print

            -   name: Build & Push (multi-arch)
                uses: docker/bake-action@v6
                env:
                    VERSION: "${{ inputs.version }}"
                    TAG: "${{ env.IMAGE_NAME }}:${{ inputs.version }}"
                with:
                    files: |
                        ./docker-bake.hcl
                        ${{ steps.keycloak.outputs.bake-file }}
                    push: true

            - name: Show published tags
              run: |
                echo "Published tags:"
                echo "${{ steps.meta.outputs.tags }}"
